name: docker-publish

on:
  workflow_dispatch:
    inputs:
      publish_latest:
        description: 'Also publish the latest tag'
        default: 'true'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Check required secrets
        if: ${{ env.DOCKERHUB_USER == '' || env.DOCKERHUB_TOKEN == '' }}
        run: |
          echo '::error::DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets are required' >&2
          exit 1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive GHCR image name
        id: ghcr
        run: |
          owner=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "image=ghcr.io/${owner}/webssh2" >> "${GITHUB_OUTPUT}"

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/billchurch/webssh2
            ${{ steps.ghcr.outputs.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish_latest == 'true' }}
            type=semver,pattern=webssh2-server-v{{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern=webssh2-server-v{{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=branch,enable=${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
            type=sha

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
