name: Downstream Notifier

on:
  release:
    types:
      - published

jobs:
  notify:
    name: Notify Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch downstream repository
        env:
          DISPATCH_REPO: ${{ secrets.DOWNSTREAM_REPO }}
          DOWNSTREAM_TOKEN: ${{ secrets.DOWNSTREAM_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          set -euo pipefail
          if [ -z "${DOWNSTREAM_TOKEN:-}" ]; then
            echo 'DOWNSTREAM_TOKEN secret is not configured' >&2
            exit 1
          fi

          if [ -z "${DISPATCH_REPO:-}" ]; then
            echo 'DISPATCH_REPO secret is not configured' >&2
            exit 1
          fi

          payload=$(jq -n --arg version "${RELEASE_TAG}" '{event_type:"webssh2-release", client_payload:{version:$version}}')

          response=$(curl --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${DOWNSTREAM_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${DISPATCH_REPO}/dispatches \
            -d "${payload}" 2>&1)

          if [ -n "${response}" ]; then
            echo "Dispatch response: ${response}"
          fi

          echo "Dispatched webssh2-release for tag ${RELEASE_TAG}"
